//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeliveryService.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره سامانه.
        /// </summary>
        public static string AboutApplication {
            get {
                return ResourceManager.GetString("AboutApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره شرکت.
        /// </summary>
        public static string AboutCompany {
            get {
                return ResourceManager.GetString("AboutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه 1.0.0.
        /// </summary>
        public static string AppilicationVersion {
            get {
                return ResourceManager.GetString("AppilicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنمای سامانه.
        /// </summary>
        public static string ApplicationHelp {
            get {
                return ResourceManager.GetString("ApplicationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Client_Address {
            get {
                return ResourceManager.GetString("Client_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ثبت کاربر.
        /// </summary>
        public static string Client_CreateDateOnUTC {
            get {
                return ResourceManager.GetString("Client_CreateDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آخرین ویرایش مشخصات کاربر.
        /// </summary>
        public static string Client_EditDateOnUTC {
            get {
                return ResourceManager.GetString("Client_EditDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر.
        /// </summary>
        public static string Client_FirstName {
            get {
                return ResourceManager.GetString("Client_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر.
        /// </summary>
        public static string Client_ID {
            get {
                return ResourceManager.GetString("Client_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی کاربر.
        /// </summary>
        public static string Client_LastName {
            get {
                return ResourceManager.GetString("Client_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت کاربر.
        /// </summary>
        public static string Client_Status {
            get {
                return ResourceManager.GetString("Client_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس کاربر.
        /// </summary>
        public static string Client_Tell {
            get {
                return ResourceManager.GetString("Client_Tell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Client_UserName {
            get {
                return ResourceManager.GetString("Client_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارووری.
        /// </summary>
        public static string CMS_Name {
            get {
                return ResourceManager.GetString("CMS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مقصد جهت ارسال سفارش.
        /// </summary>
        public static string Delivery_Address {
            get {
                return ResourceManager.GetString("Delivery_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ارجاع سفارش.
        /// </summary>
        public static string Delivery_CreatedDateOnUTC {
            get {
                return ResourceManager.GetString("Delivery_CreatedDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ورود به سیستم ارسال سفارش.
        /// </summary>
        public static string Delivery_DeliveryCreateDateOnUtc {
            get {
                return ResourceManager.GetString("Delivery_DeliveryCreateDateOnUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات ارسال.
        /// </summary>
        public static string Delivery_DeliveryIssue {
            get {
                return ResourceManager.GetString("Delivery_DeliveryIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان رویت ارسال.
        /// </summary>
        public static string Delivery_DeliverySeenDateOnUTC {
            get {
                return ResourceManager.GetString("Delivery_DeliverySeenDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Delivery_ID {
            get {
                return ResourceManager.GetString("Delivery_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر سفارش.
        /// </summary>
        public static string Delivery_Img {
            get {
                return ResourceManager.GetString("Delivery_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس پیک.
        /// </summary>
        public static string Delivery_NuncioAddress {
            get {
                return ResourceManager.GetString("Delivery_NuncioAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان دریافت سفارش توسط مشتری.
        /// </summary>
        public static string Delivery_NuncioAtClientDateOnUTC {
            get {
                return ResourceManager.GetString("Delivery_NuncioAtClientDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان حضور پیک در مرکز.
        /// </summary>
        public static string Delivery_NuncioAtStationDateOnUTC {
            get {
                return ResourceManager.GetString("Delivery_NuncioAtStationDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مرکز پیک.
        /// </summary>
        public static string Delivery_NuncioName {
            get {
                return ResourceManager.GetString("Delivery_NuncioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی پیک.
        /// </summary>
        public static string Delivery_NuncioOwnerName {
            get {
                return ResourceManager.GetString("Delivery_NuncioOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس پیک.
        /// </summary>
        public static string Delivery_NuncioTell {
            get {
                return ResourceManager.GetString("Delivery_NuncioTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ارسال پیک.
        /// </summary>
        public static string Delivery_SendNuncioDateOnUTC {
            get {
                return ResourceManager.GetString("Delivery_SendNuncioDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پیگیری سفارش.
        /// </summary>
        public static string Delivery_TrackingCode {
            get {
                return ResourceManager.GetString("Delivery_TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ورود به سیستم ارسال سفارش.
        /// </summary>
        public static string DeliveryManagment_DeliveryCreateDateOnUtc {
            get {
                return ResourceManager.GetString("DeliveryManagment_DeliveryCreateDateOnUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سیستم ارسال سفارش.
        /// </summary>
        public static string DeliveryManagment_DeliveryIssue {
            get {
                return ResourceManager.GetString("DeliveryManagment_DeliveryIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان رویت سفارش در سیستم ارسال سفارش.
        /// </summary>
        public static string DeliveryManagment_DeliverySeenDateOnUTC {
            get {
                return ResourceManager.GetString("DeliveryManagment_DeliverySeenDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس مرکز پیک.
        /// </summary>
        public static string DeliveryManagment_NuncioAddress {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تحویل سفارش به پیک توسط مشتری.
        /// </summary>
        public static string DeliveryManagment_NuncioAtClientDateOnUTC {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioAtClientDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان حضور پیک در مرکز ارسال سفارش.
        /// </summary>
        public static string DeliveryManagment_NuncioAtStationDateOnUTC {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioAtStationDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مرکز پیک.
        /// </summary>
        public static string DeliveryManagment_NuncioName {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی پیک.
        /// </summary>
        public static string DeliveryManagment_NuncioOwnerCompleteName {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioOwnerCompleteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس پیک.
        /// </summary>
        public static string DeliveryManagment_NuncioTell {
            get {
                return ResourceManager.GetString("DeliveryManagment_NuncioTell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تحویل سفارش به پیک.
        /// </summary>
        public static string DeliveryManagment_SendNuncioDateOnUTC {
            get {
                return ResourceManager.GetString("DeliveryManagment_SendNuncioDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیدا کن.
        /// </summary>
        public static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راهنما.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کاربر جدید.
        /// </summary>
        public static string PageTittle_AddClient {
            get {
                return ResourceManager.GetString("PageTittle_AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف مرکز جدید.
        /// </summary>
        public static string PageTittle_AddStation {
            get {
                return ResourceManager.GetString("PageTittle_AddStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیگیری سفارش کاربران.
        /// </summary>
        public static string PageTittle_ClientActivityReport {
            get {
                return ResourceManager.GetString("PageTittle_ClientActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت کسب اطلاعات بیشتر با پشتیبانی تماس حاصل فرمایید.
        /// </summary>
        public static string PageTittle_ContactUS {
            get {
                return ResourceManager.GetString("PageTittle_ContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string PageTittle_Dashboard {
            get {
                return ResourceManager.GetString("PageTittle_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات ارسال مورد نظر.
        /// </summary>
        public static string PageTittle_DeliveryDetail {
            get {
                return ResourceManager.GetString("PageTittle_DeliveryDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست ارسال ها.
        /// </summary>
        public static string PageTittle_DeliveryList {
            get {
                return ResourceManager.GetString("PageTittle_DeliveryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات کاربر مورد نظر.
        /// </summary>
        public static string PageTittle_DetailClient {
            get {
                return ResourceManager.GetString("PageTittle_DetailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش جزئیات مرکز مورد نظر.
        /// </summary>
        public static string PageTittle_DetailStation {
            get {
                return ResourceManager.GetString("PageTittle_DetailStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصات کاربر مورد نظر.
        /// </summary>
        public static string PageTittle_EditClient {
            get {
                return ResourceManager.GetString("PageTittle_EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مرکز مورد نظر.
        /// </summary>
        public static string PageTittle_EditStation {
            get {
                return ResourceManager.GetString("PageTittle_EditStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافتن کاربر.
        /// </summary>
        public static string PageTittle_FindClient {
            get {
                return ResourceManager.GetString("PageTittle_FindClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران.
        /// </summary>
        public static string PageTittle_ListClient {
            get {
                return ResourceManager.GetString("PageTittle_ListClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست مراکز.
        /// </summary>
        public static string PageTittle_ListStation {
            get {
                return ResourceManager.GetString("PageTittle_ListStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت حساب کاربری.
        /// </summary>
        public static string PageTittle_ManageAccount {
            get {
                return ResourceManager.GetString("PageTittle_ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درخواست ها.
        /// </summary>
        public static string PageTittle_RequestManagement {
            get {
                return ResourceManager.GetString("PageTittle_RequestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مرکز.
        /// </summary>
        public static string PageTittle_SingleStationResponse {
            get {
                return ResourceManager.GetString("PageTittle_SingleStationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مراکز.
        /// </summary>
        public static string PageTittle_StationResponse {
            get {
                return ResourceManager.GetString("PageTittle_StationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش جزئیات عملکرد مرکز مورد نظر.
        /// </summary>
        public static string PageTittle_StationResponseDetail {
            get {
                return ResourceManager.GetString("PageTittle_StationResponseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس درخواست ارسالی.
        /// </summary>
        public static string RequestManagment_Address {
            get {
                return ResourceManager.GetString("RequestManagment_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پاسخ کاربر .
        /// </summary>
        public static string RequestManagment_ClientResponseDateOnUTC {
            get {
                return ResourceManager.GetString("RequestManagment_ClientResponseDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تایید کاربر.
        /// </summary>
        public static string RequestManagment_ClientStatus {
            get {
                return ResourceManager.GetString("RequestManagment_ClientStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل جغرافیای مرکز.
        /// </summary>
        public static string RequestManagment_Coordinates {
            get {
                return ResourceManager.GetString("RequestManagment_Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت درخواست.
        /// </summary>
        public static string RequestManagment_CreatedDateOnUtc {
            get {
                return ResourceManager.GetString("RequestManagment_CreatedDateOnUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر درخواست.
        /// </summary>
        public static string RequestManagment_Img {
            get {
                return ResourceManager.GetString("RequestManagment_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت پرداخت.
        /// </summary>
        public static string RequestManagment_IsSetted {
            get {
                return ResourceManager.GetString("RequestManagment_IsSetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت پیشنهادی.
        /// </summary>
        public static string RequestManagment_Price {
            get {
                return ResourceManager.GetString("RequestManagment_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پردازش درخواست.
        /// </summary>
        public static string RequestManagment_ProcessingDateOnUTC {
            get {
                return ResourceManager.GetString("RequestManagment_ProcessingDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ رد درخواست.
        /// </summary>
        public static string RequestManagment_RejectDateOnUtc {
            get {
                return ResourceManager.GetString("RequestManagment_RejectDateOnUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ایجاد درخواست.
        /// </summary>
        public static string RequestManagment_RequestCreatedDateOnUtc {
            get {
                return ResourceManager.GetString("RequestManagment_RequestCreatedDateOnUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سفارش.
        /// </summary>
        public static string RequestManagment_RequestId {
            get {
                return ResourceManager.GetString("RequestManagment_RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات مرکز در خصوص سفارش.
        /// </summary>
        public static string RequestManagment_ResponseIssue {
            get {
                return ResourceManager.GetString("RequestManagment_ResponseIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان مشاهده درخواست توسط اپراتور.
        /// </summary>
        public static string RequestManagment_SeenDateOnUTC {
            get {
                return ResourceManager.GetString("RequestManagment_SeenDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تایید مرکز.
        /// </summary>
        public static string RequestManagment_StationStatus {
            get {
                return ResourceManager.GetString("RequestManagment_StationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تایید کاربر.
        /// </summary>
        public static string RequestManagment_Status {
            get {
                return ResourceManager.GetString("RequestManagment_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پیگیری.
        /// </summary>
        public static string RequestManagment_TrackingCode {
            get {
                return ResourceManager.GetString("RequestManagment_TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انتظار برای پاسخ کاربر.
        /// </summary>
        public static string RequestManagment_WaitingForClientDateOnUTC {
            get {
                return ResourceManager.GetString("RequestManagment_WaitingForClientDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Station_Address {
            get {
                return ResourceManager.GetString("Station_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصات جغرافیایی.
        /// </summary>
        public static string Station_Coordinate {
            get {
                return ResourceManager.GetString("Station_Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد حساب.
        /// </summary>
        public static string Station_CreateDateOnUTC {
            get {
                return ResourceManager.GetString("Station_CreateDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ویرایش اعمال شده.
        /// </summary>
        public static string Station_EditDateOnUTC {
            get {
                return ResourceManager.GetString("Station_EditDateOnUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Station_FirstName {
            get {
                return ResourceManager.GetString("Station_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مرکز.
        /// </summary>
        public static string Station_ID {
            get {
                return ResourceManager.GetString("Station_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string Station_LastName {
            get {
                return ResourceManager.GetString("Station_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مرکز.
        /// </summary>
        public static string Station_StationName {
            get {
                return ResourceManager.GetString("Station_StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Station_Status {
            get {
                return ResourceManager.GetString("Station_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Station_Tell {
            get {
                return ResourceManager.GetString("Station_Tell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string Station_UserName {
            get {
                return ResourceManager.GetString("Station_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان پاسخ گویی مراکز به درخواست ها.
        /// </summary>
        public static string StationsResponsibilaty {
            get {
                return ResourceManager.GetString("StationsResponsibilaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت و ارسال.
        /// </summary>
        public static string Ticket_ReplySend {
            get {
                return ResourceManager.GetString("Ticket_ReplySend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز دسترسی به این بخش را ندارید.
        /// </summary>
        public static string Unauthorized_Access_Error {
            get {
                return ResourceManager.GetString("Unauthorized_Access_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف مرکز جدید.
        /// </summary>
        public static string View_AddStation {
            get {
                return ResourceManager.GetString("View_AddStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان خاطر دارید ؟.
        /// </summary>
        public static string View_AreYouShure {
            get {
                return ResourceManager.GetString("View_AreYouShure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان خاطر دارید که درخواست را تایید کنید ؟.
        /// </summary>
        public static string View_AreYouShureToAccept {
            get {
                return ResourceManager.GetString("View_AreYouShureToAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از پرداخت مبلغ اطمینان خاطر دارید ؟.
        /// </summary>
        public static string View_AreYouShureToPay {
            get {
                return ResourceManager.GetString("View_AreYouShureToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان خاطر دارید که درخواست را رد کنید ؟.
        /// </summary>
        public static string View_AreYouShureToReject {
            get {
                return ResourceManager.GetString("View_AreYouShureToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراحی و توسعه دلیوری.
        /// </summary>
        public static string View_Author {
            get {
                return ResourceManager.GetString("View_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد کاربران.
        /// </summary>
        public static string View_ClientActivityReport {
            get {
                return ResourceManager.GetString("View_ClientActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string View_ClientManagement {
            get {
                return ResourceManager.GetString("View_ClientManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string View_Close {
            get {
                return ResourceManager.GetString("View_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string View_Dashboard {
            get {
                return ResourceManager.GetString("View_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست ارسال ها.
        /// </summary>
        public static string View_DeliveryList {
            get {
                return ResourceManager.GetString("View_DeliveryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیریت دلیوری.
        /// </summary>
        public static string View_Description {
            get {
                return ResourceManager.GetString("View_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مرکز .
        /// </summary>
        public static string View_EditStation {
            get {
                return ResourceManager.GetString("View_EditStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران.
        /// </summary>
        public static string View_ListClient {
            get {
                return ResourceManager.GetString("View_ListClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست مراکز.
        /// </summary>
        public static string View_ListStation {
            get {
                return ResourceManager.GetString("View_ListStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منوی مدیریت.
        /// </summary>
        public static string View_MainNavigation_Tittle {
            get {
                return ResourceManager.GetString("View_MainNavigation_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشگیری.
        /// </summary>
        public static string View_Report {
            get {
                return ResourceManager.GetString("View_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درخواست ها.
        /// </summary>
        public static string View_RequestManagement {
            get {
                return ResourceManager.GetString("View_RequestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مرکز.
        /// </summary>
        public static string View_SingleStationActivityReport {
            get {
                return ResourceManager.GetString("View_SingleStationActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش عملکرد مراکز.
        /// </summary>
        public static string View_StationActivityReport {
            get {
                return ResourceManager.GetString("View_StationActivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت مراکز.
        /// </summary>
        public static string View_StationManagement {
            get {
                return ResourceManager.GetString("View_StationManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنل مدیریت.
        /// </summary>
        public static string View_Tittle {
            get {
                return ResourceManager.GetString("View_Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد مورد نظر را تکمیل کنید.
        /// </summary>
        public static string View_ValidationError {
            get {
                return ResourceManager.GetString("View_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلی.
        /// </summary>
        public static string View_Yes {
            get {
                return ResourceManager.GetString("View_Yes", resourceCulture);
            }
        }
    }
}
