//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUTC { get; set; }
        public Nullable<System.DateTime> EditedDateOnUTC { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string F_userId { get; set; }
        public string RndValue { get; set; }
        public string AndroidId { get; set; }
    
        public virtual ICollection<Request> Requests { get; set; }
    }
}
