//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public string StationResponse { get; set; }
        public string NuncioResponse { get; set; }
        public Nullable<int> F_NuncioId { get; set; }
        public Nullable<int> F_StationId { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUTC { get; set; }
        public Nullable<System.DateTime> SeenDateOnUTC { get; set; }
        public Nullable<System.DateTime> SendNuncioDateOnUTC { get; set; }
        public Nullable<System.DateTime> NuncioAtStationDateOnUTC { get; set; }
        public Nullable<System.DateTime> NuncioAtClientDateOnUTC { get; set; }
        public string DeliveryIssue { get; set; }
    
        public virtual Nuncio Nuncio { get; set; }
        public virtual Request Request { get; set; }
        public virtual Station Station { get; set; }
    }
}
