//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public int Id { get; set; }
        public string Image { get; set; }
        public string Address { get; set; }
        public string Coordinates { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUTC { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> F_ClientId { get; set; }
        public string TrackingCode { get; set; }
        public Nullable<bool> isSetteld { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual ICollection<Response> Responses { get; set; }
    }
}
