//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Deliveries = new HashSet<Delivery>();
            this.Responses = new HashSet<Response>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string StaionName { get; set; }
        public string Tell { get; set; }
        public string Address { get; set; }
        public string Coordinates { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDateOnUTC { get; set; }
        public Nullable<System.DateTime> EditedDateOnUTC { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string F_UserId { get; set; }
    
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<Response> Responses { get; set; }
    }
}
